### ISSUE TITLE
Create PHP Artisan command to generate compatable .env 

### ISSUE THREAD

**Issue by xdega** [xdega/laravel-with-docker#4]
Currently, the README.md outlines instruction on creating a .env file for local development. While it isn't too challenging to copy and paste into a file, it would be more streamlined to allow a simple `docker-compose run app php artisan env:local` command to do this instead.

**Comment by marcusmyers** [comment]
What about a `script/bootstrap` that sets up everything for development?

**Comment by xdega** [comment]
@marcusmyers Excellent idea.

**Comment by xdega** [comment]
Issue addressed.
